import {
  LayoutDashboard,
  ShoppingCart,
  Package,
  PackagePlus,
  HandCoins,
  BarChart3,
  CreditCard,
  Settings,
  Receipt,
  PiggyBank,
  TriangleAlert,
  TrendingUp,
  TrendingDown,
  CircleCheck,
  Users,
  Plus,
  ArrowRight,
  ArrowLeft,
  Search,
  XCircle,
  Download,
  History,
  Trophy,
  Tags,
  Tablet,
  MessageCircle,
  MessageSquare,
  Send,
  ShoppingBasket,
  RefreshCw,
  ClipboardList,
} from "lucide-react";

/**
 * Central registry of Lucide icons used across the app — one semantic
 * name per concept rather than importing `lucide-react` ad-hoc per file,
 * so a mapping only needs fixing here. This is shadcn's own proposed
 * icon library (`iconLibrary: "lucide"` in components.json) — the app
 * briefly used flat-color-icons (react-icons/fc) for content icons, but
 * reverted to plain monochrome Lucide, matching the shadcn Nova preset.
 */
export const Icons = {
  dashboard: LayoutDashboard,
  pos: ShoppingCart,
  product: Package,
  stock: PackagePlus,
  credit: HandCoins,
  reports: BarChart3,
  subscription: CreditCard,
  settings: Settings,

  sales: Receipt,
  profit: PiggyBank,
  alert: TriangleAlert,
  trendUp: TrendingUp,
  trendDown: TrendingDown,
  success: CircleCheck,
  customers: Users,
  add: Plus,
  next: ArrowRight,
  back: ArrowLeft,
  search: Search,
  cancelled: TriangleAlert,
  failed: XCircle,
  download: Download,
  history: History,
  topRated: Trophy,
  folder: Tags,
  tablet: Tablet,
  support: MessageCircle,
  sms: MessageSquare,
  callback: Send,
  transactionCount: Receipt,
  avgBasket: ShoppingBasket,
  sync: RefreshCw,
  setup: ClipboardList,
} as const;
